name: Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build --scope @9renpoto/slides

      - name: Publish to Cloudflare Pages
        id: cloudflare_pages_deploy
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: slides-9renpoto-win
          directory: apps/slides/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
