name: 'Check spelling'
on:
  pull_request:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v5
        with:
          files: |
            {apps,packages}/**/*.{ts,js}
            !dist/**/*.{ts,js}
          incremental_files_only: false
